"""
Molecular Architect RL: MM-GBSA Relative Binding Free Energy (Stage-3 Oracle).

This script serves as the apex physics tier of the oracle pipeline, evaluating the top 
surviving molecules that have successfully passed all preceding filters (raw docking, 
PoseBusters validation, and the mechanistic interaction fingerprint filter).

How it works:
Instead of relying on heuristic docking scores, this module orchestrates a rigorous 
physics-based evaluation by bridging to the external `PhysDock` stack. 
1. DiffDock-L is used to generate highly refined, flexible poses.
2. OpenMM relaxes these poses and computes an MM-GBSA relative binding free energy 
   (molecular-mechanics interaction energy + generalised-Born solvation). Note that 
   entropy is omitted, making this a relative, rather than absolute, calculation.
3. Boltz-2 co-folds the complex to provide an orthogonal confidence signal (ipTM).

This yields a meaningfully superior ranker compared to standard docking and produces 
the correct, high-fidelity labels required to train the surrogate model for the final 
active-learning round. Architecturally, this module is a thin wrapper over 
`oracle.physdock_bridge` that shells into an isolated `physdock` Conda environment.
"""

import json
import os
from typing import Dict, List

from oracle.physdock_bridge import run_physics_on_topk


def mmgbsa_on(smiles: List[str], physdock_repo: str, conda_env: str = "physdock", workdir: str = "results/physics", n: int = 8) -> Dict:
    """
    Executes the advanced physics evaluation tier (DiffDock-L -> OpenMM -> Boltz-2) on top candidates.
    
    Slices the input list to retain only the top `n` molecules to conserve massive compute 
    resources. It delegates the actual heavy lifting to the `run_physics_on_topk` bridge 
    function. Once the external pipeline finishes, it locates the generated `summary.json`, 
    parses the resulting MM-GBSA dG_rel and Boltz ipTM metrics, and appends them to the 
    info dictionary.
    
    Args:
        smiles (List[str]): A list of SMILES strings that passed all previous Stage-2 filters.
        physdock_repo (str): The absolute or relative file path to the local PhysDock repository.
        conda_env (str, optional): The name of the isolated Conda environment containing the physics dependencies. Defaults to "physdock".
        workdir (str, optional): The directory where intermediate structures and results will be saved. Defaults to "results/physics".
        n (int, optional): The maximum number of molecules to evaluate, acting as a compute budget cap. Defaults to 8.
        
    Returns:
        Dict: A summary dictionary containing pipeline execution status and the parsed 
        thermodynamic/folding metrics under the "mmgbsa" key.
        
    Example:
        >>> top_smiles = ["CC1=C(C=C(C=C1)F)NC(=O)C2=CC=C(C=C2)C3=CN=C(N=C3)N4CCNCC4"]
        >>> results = mmgbsa_on(top_smiles, physdock_repo="/path/to/PhysDock")
    """
    # -------------------------------------------------------------------------------------
    # Physics Pipeline Delegation
    # Truncate the candidate list and invoke the external PhysDock bridge script.
    # -------------------------------------------------------------------------------------
    info = run_physics_on_topk(smiles[:n], physdock_repo=physdock_repo, conda_env=conda_env, workdir=workdir, run_boltz=True) # Delegate execution to the bridge, passing strictly the top 'n' SMILES, environment settings, and requesting a Boltz-2 run

    # -------------------------------------------------------------------------------------
    # Result Extraction and Parsing
    # Locate the output JSON file generated by PhysDock and merge it into the python dict.
    # -------------------------------------------------------------------------------------
    sp = os.path.join(workdir, "summary.json")                                              # Construct the absolute path to the expected output summary JSON file
    
    # Check if the summary file exists, and if so, attempt to load its contents into the 
    # info dictionary (containing the parsed thermodynamic/folding metrics under the "mmgbsa" key.)
    if os.path.exists(sp):                                                                  # Check if the external pipeline successfully generated the summary file on disk
        try:                                                                                # Wrap the file I/O operations to prevent parsing errors from crashing the main loop
            info["mmgbsa"] = json.load(open(sp))                                            # Open the JSON file, parse its contents, and attach it to the info dictionary under the "mmgbsa" key
        except Exception:                                                                   # Catch any exceptions raised by missing files or corrupted JSON formatting
            pass                                                                            # Fail silently to allow the pipeline to continue execution without physics metrics
    
    # Return the populated dictionary containing bridge status and appended physics metrics
    return info                                                                             