"""
==================================
Synthesizability and Realism Gate
==================================

This module acts as a critical safety and realism filter (a "gate") applied to the 
final molecular graphs generated by the reinforcement learning (RL) agent. 
During Phase-1 training, the RL agent often discovered "reward hacks"—exploiting 
simple 2D descriptors like QED by generating highly unstable or impossible 
chemical motifs (e.g., carbon-sulfur triple bonds, C#S#S#C chains) that mathematically 
scored well but could never exist in a laboratory. 

This script systematically kills that failure mode by:
1. Hard-banning explicit, impossible SMARTS patterns discovered from prior trajectories.
2. Applying the Synthetic Accessibility (SA) Score (Ertl & Schuffenhauer) to penalize 
   or outright reject molecules that are fundamentally unsynthesizable.
3. Applying PAINS (Pan Assay Interference Compounds) and BRENK structural alerts 
   via the RDKit FilterCatalog to penalize reactive, toxic, or assay-interfering substructures.

The primary entry point is the `synth_gate` function, which is designed to be 
combined with the affinity reward downstream to shape the final policy gradient.
"""

import os                                                                                   # Import the OS module for interacting with the operating system
import sys                                                                                  # Import the sys module to manipulate the Python runtime environment
from rdkit import Chem                                                                      # Import the core chemistry module from RDKit for molecule manipulation
from rdkit.Chem import RDConfig, FilterCatalog                                              # Import RDKit configuration paths and the structural alert catalog module


# The SA_Score module is not in the main RDKit namespace; must dynamically append its path.
sys.path.append(os.path.join(RDConfig.RDContribDir, "SA_Score"))                            # Append the RDKit Contrib directory to the Python path to locate sascorer
import sascorer  # noqa: E402  (RDKit Contrib module)                                       # Import the Synthetic Accessibility scorer module from the Contrib folder

#-------------------------------------------------------------------------------------------------------------------------
# Hard-Banned Reward Hacking Motifs: Define specific graph structures that the agent previously abused to inflate rewards.
#-------------------------------------------------------------------------------------------------------------------------
_BANNED_SMARTS = [                                                # Initialize a list of raw SMARTS string patterns representing banned motifs
    "[#6]#[#16]",                                                 # Ban carbon-sulfur triple bonds (C#S), a common descriptor-hacking artifact
    "[#16]#[#16]",                                                # Ban sulfur-sulfur triple bonds (S#S), chemically unrealistic
    "[#6]=[#6]=[#6]=*",                                           # Ban extended cumulene chains (>2 consecutive double bonds) which are highly unstable in reality
    "*#*#*",                                                      # Ban consecutive triple bonds (cumulated/heterocumulenes) to prevent extreme linear chain hacks
    "[#7]=[#7]=[#7]",                                             # Ban extended azide-like nitrogen chains to prevent explosive motifs
]                                                                 
_BANNED = [Chem.MolFromSmarts(s) for s in _BANNED_SMARTS]         # Pre-compile the raw SMARTS strings into RDKit Mol objects for faster matching

# --------------------------------------------------------------------------------------------------------------------------------------------------
# PAINS and BRENK Structural Alert Catalog Configuration: Set up the RDKit FilterCatalog to cross-reference against known problematic substructures.
# --------------------------------------------------------------------------------------------------------------------------------------------------
_params = FilterCatalog.FilterCatalogParams()                                               # Instantiate a fresh configuration parameters object for the filter catalog
_params.AddCatalog(FilterCatalog.FilterCatalogParams.FilterCatalogs.PAINS)                  # Add the Pan Assay Interference Compounds (PAINS) library to the catalog
_params.AddCatalog(FilterCatalog.FilterCatalogParams.FilterCatalogs.BRENK)                  # Add the Brenk library of toxic/reactive fragments to the catalog
_CATALOG = FilterCatalog.FilterCatalog(_params)                                             # Build the final FilterCatalog object using the configured PAINS+BRENK parameters

# ------------------------------------------------------------------------------------------------------------------
# System Tunables & Hyperparameters: Define the boundaries and penalty weights for the synthesizability constraints.
# ------------------------------------------------------------------------------------------------------------------
SA_HARD_MAX = 6.0           # Set the absolute maximum Synthetic Accessibility score before immediate rejection; above this -> reward zeroed (nothing a chemist would attempt)  
SA_FREE_MAX = 3.5           # Set the threshold below which molecules incur zero synthetic complexity penalty; at/below this -> no SA penalty (real drugs ~1.5-3.5)
ALERT_DECAY = 0.7           # Set the (soft) multiplicative decay factor applied per PAINS/BRENK alert found
BANNED_PENALTY = -2.0       # Set the fixed negative terminal reward value for molecules that fail the hard gate


def sa_score(mol) -> float:
    """
    Calculates the Synthetic Accessibility (SA) score for a given molecule.
    
    Passes the RDKit Mol object to the Ertl & Schuffenhauer `sascorer` from the RDKit 
    contrib directory. It wraps the execution in a try-except block to gracefully handle 
    unstable topological graph states that might crash the algorithm.
    
    Args:
        mol (Chem.Mol): The RDKit molecule object to be scored.
        
    Returns:
        float: The computed SA score. Ranges theoretically from 1.0 (very easy to synthesize) 
        to 10.0 (impossible). Returns 10.0 upon computation failure.
        
    Example:
        >>> m = Chem.MolFromSmiles("CC(=O)Oc1ccccc1C(=O)O") # Aspirin
        >>> score = sa_score(m)
        >>> print(round(score, 2))
        1.58
    """
    try:                                                                                    # Wrap the evaluation in a try block to handle RDKit graph analysis errors
        return float(sascorer.calculateScore(mol))                                          # Calculate the SA score using the contrib module and cast to a python float
    except Exception:                                                                       # Catch any underlying exceptions raised during the scoring process
        return 10.0                                                                         # Return the maximum possible SA score (10.0 = impossible) as a safe fallback


def has_banned_motif(mol) -> bool:
    """
    Checks if the molecule contains any explicitly banned structural hacks.
    
    Iterates through the pre-compiled `_BANNED` list of RDKit molecule objects (derived 
    from the SMARTS patterns defined at the module level) and evaluates `HasSubstructMatch`. 
    If any pattern matches, it immediately flags the molecule.
    
    Args:
        mol (Chem.Mol): The RDKit molecule object to inspect.
        
    Returns:
        bool: True if at least one banned motif is found, False otherwise.
        
    Example:
        >>> bad_m = Chem.MolFromSmiles("CCS#C") # Contains banned C#S
        >>> has_banned_motif(bad_m)
        True
    """
    # Motif Matching Logic: Iterate through pre-compiled patterns (BANNED SMARTS list), and return True if any substructure matches
    return any(p is not None and mol.HasSubstructMatch(p) for p in _BANNED)                 


def num_alerts(mol) -> int:
    """
    Counts the number of Pan Assay Interference (PAINS) or BRENK structural alerts.
    
    Queries the global RDKit `FilterCatalog` initialized at startup. It applies 
    the combined library of hundreds of known problematic substructures against the 
    molecule to tally a hit count.
    
    Args:
        mol (Chem.Mol): The RDKit molecule object to evaluate.
        
    Returns:
        int: The total count of unique structural alerts triggered by the molecule.
        
    Example:
        >>> m = Chem.MolFromSmiles("c1ccccc1") # Benzene
        >>> num_alerts(m)
        0
    """
    # Alert Tallying Logic: Query the PAINS/BRENK filter catalog for matches and return the total count of triggered alerts
    return len(_CATALOG.GetMatches(mol))


def synth_gate(mol):
    """
    The primary gatekeeping function evaluating a molecule's realism and synthesizability.
    
    First checks for severe violations (None objects, banned motifs, excessively high 
    SA scores). If these hard checks fail, it returns `hard_ok=False`. If it passes, 
    it scales a soft reward multiplier. The soft multiplier decays linearly based on 
    the SA score (between SA_FREE_MAX and SA_HARD_MAX) and decays exponentially 
    for every structural alert found.
    
    Args:
        mol (Chem.Mol): The RDKit molecule object generated by the RL policy.
        
    Returns:
        Tuple[bool, float, dict]:
            - hard_ok (bool): True if the molecule passes hard constraints, False if it is banned.
            - soft_multiplier (float): A bounded value [0.0, 1.0] to scale downstream rewards.
            - info (dict): Telemetry metadata (e.g., reasons for failure, exact scores).
            
    Example:
        >>> m = Chem.MolFromSmiles("CC(=O)Oc1ccccc1C(=O)O") # Aspirin
        >>> is_ok, mult, info = synth_gate(m)
        >>> print(is_ok)
        True
        >>> print(round(mult, 2))   # < 1.0 because aspirin trips one BRENK alert (its acetate ester)
        0.7
    """
    # ---------------------------------------------------------------------------------------------------------------------------------
    # Hard Rejection Criteria: Immediately fail the molecule if it triggers None objects, banned motifs, or excessively high SA scores.
    # ---------------------------------------------------------------------------------------------------------------------------------
    if mol is None:                                                                         # Check if the provided molecule object is invalid or None
        return False, 0.0, {"reason": "none"}                                               # Reject the molecule, apply zero soft multiplier, and return the failure reason
    if has_banned_motif(mol):                                                               # Check if the molecule contains any of the hard-banned reward-hacking motifs
        return False, 0.0, {"reason": "banned_motif"}                                       # Reject the molecule, apply zero soft multiplier, and log the banned motif hit
    sa = sa_score(mol)                                                                      # Compute the Synthetic Accessibility (SA) score for the given molecule
    if sa > SA_HARD_MAX:                                                                    # Check if the SA score exceeds the absolute maximum allowable threshold
        return False, 0.0, {"reason": "sa_too_high", "sa": sa}                              # Reject the molecule, apply zero soft multiplier, and record the excessive SA score
    
    # --------------------------------------------------------------------------------------------------------------
    # Soft Penalty Scaling: Linearly decay reward for moderate complexity, exponentially decay for toxic alerts.
    # --------------------------------------------------------------------------------------------------------------
    sa_pen = max(0.0, min(1.0, (SA_HARD_MAX - sa) / (SA_HARD_MAX - SA_FREE_MAX)))           # Calculate a linear soft penalty multiplier scaling from 1.0 (free) down to 0.0 (hard max)
    n_alerts = num_alerts(mol)                                                              # Retrieve the total number of PAINS/BRENK structural alerts triggered by the molecule
    # Combine the SA penalty and the exponentially decaying alert penalty into a single multiplier
    soft = sa_pen * (ALERT_DECAY ** n_alerts)                                               
    return True, float(soft), {"sa": sa, "alerts": n_alerts}                                # Approve the molecule, return the final calculated soft multiplier, and log the metrics


if __name__ == "__main__":
    """
    Executable testing block to test the synth_gate function against known reward-hacking 
    molecules and real drug references. Runs automatically if the script is executed directly to verify functionality.
    """
    # Agent Failure Modes Database: Define a set of known reward-hacking molecules that previously exploited the RL agent's scoring function.
    hacks = [                                                                               
        "OCCC1CC2CC3=C(S#COCl)CC12C3",                                                      # Define a hacked SMILES string containing an impossible carbon-sulfur triple bond
        "C#S#S#CC12OC34OC5(CNCC)C6C1C53C2C64F",                                             # Define a heavily hacked SMILES string featuring an absurd S#S triple bond chain
        "FCOC#S#S#COC12CCC1CC2c1c[nH]o1",                                                   # Define another hacked SMILES string demonstrating the agent's cumulene exploitation
    ]                                                                                       # Close the list of hacked SMILES test cases
    
    # Real Drug Reference Database: Define a small set of real-world drug molecules to validate that the synth_gate allows chemically valid structures.
    drugs = {                                                                               
        "aspirin": "CC(=O)Oc1ccccc1C(=O)O",                                                 # Define the SMILES string for aspirin (acetylsalicylic acid)
        "imatinib": "Cc1ccc(NC(=O)c2ccc(CN3CCN(C)CC3)cc2)cc1Nc1nccc(-c2cccnc2)n1",          # Define the SMILES string for imatinib (Gleevec), a complex modern kinase inhibitor
        "ibuprofen": "CC(C)Cc1ccc(C(C)C(=O)O)cc1",                                          # Define the SMILES string for ibuprofen, a standard NSAID
    }                                                                                       # Close the dictionary of real drug test cases
    
    # Gateway Validation Printing: Pass both datasets through the synth_gate and output the terminal validation decisions.
    print("HACKS (expect hard_ok=False):")                                                  # Print a header indicating that the upcoming test cases should fail the synth gate
    for s in hacks:                                                                         # Iterate over each hacked SMILES string in the test list
        print(" ", s, "->", synth_gate(Chem.MolFromSmiles(s)))                              # Parse the SMILES to an RDKit Mol, evaluate it with the synth gate, and print the results
    print("DRUGS (expect hard_ok=True):")                                                   # Print a header indicating that the upcoming real-world drugs should pass the gate
    for n, s in drugs.items():                                                              # Iterate over the drug names and their corresponding SMILES strings in the dictionary
        print(" ", f"{n:10s}", synth_gate(Chem.MolFromSmiles(s)))                           # Parse the drug SMILES, evaluate it with the synth gate, and print the formatted results